/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedDeclaracoesIdRouteImport } from './routes/_authenticated/declaracoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeclaracoesIdRoute =
  AuthenticatedDeclaracoesIdRouteImport.update({
    id: '/declaracoes/$id',
    path: '/declaracoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/declaracoes/$id': typeof AuthenticatedDeclaracoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/declaracoes/$id': typeof AuthenticatedDeclaracoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/declaracoes/$id': typeof AuthenticatedDeclaracoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipe' | '/painel' | '/declaracoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipe' | '/painel' | '/declaracoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/equipe'
    | '/_authenticated/painel'
    | '/_authenticated/declaracoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/declaracoes/$id': {
      id: '/_authenticated/declaracoes/$id'
      path: '/declaracoes/$id'
      fullPath: '/declaracoes/$id'
      preLoaderRoute: typeof AuthenticatedDeclaracoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedDeclaracoesIdRoute: typeof AuthenticatedDeclaracoesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedDeclaracoesIdRoute: AuthenticatedDeclaracoesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
